title: dannytaylor
theme: just-the-docs
url: https://wiki.mclegoman.com
favicon_ico: "https://mclegoman.com/assets/img/favicon.png"
search_enabled: true
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit"
gh_edit_repository: "https://github.com/legotaylor/wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
color_scheme: dark
nav_external_links:
  - title: Home
    url: https://mclegoman.com
