title: dannytaylor
theme: just-the-docs
languages: ["en"]
default_lang: "en"
lang_from_path: true
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap"]
parallel_localization: true
url: https://wiki.mclegoman.com
favicon_ico: "https://mclegoman.com/assets/img/favicon.png"
search_enabled: true
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit"
gh_edit_repository: "https://github.com/legotaylor/wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
color_scheme: dark
callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  author:
    title: Author
    color: pink
  authors:
    title: Authors
    color: pink
  contributor:
    title: Contributor
    color: lime
  contributors:
    title: Contributors
    color: lime
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
plugins:
  - jekyll-polyglot
  - jekyll-redirect-from
nav_external_links:
  - title: Home
    url: https://mclegoman.com
